name: Rails CI/CD

on:
  push:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Pull latest code
        run: |
          cd /home/ubuntu/s3-rails-app
          git pull origin master

      - name: Install dependencies
        run: |
          source ~/.rvm/scripts/rvm
          cd /home/ubuntu/s3-rails-app
          bundle install

      - name: Restart Puma
        run: sudo systemctl restart puma
