name: Rails CI/CD

on:
  push:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        run: |
          source ~/.rvm/scripts/rvm
          rvm use 3.2.2

      - name: Install dependencies
        run: |
          source ~/.rvm/scripts/rvm
          bundle install

      - name: Write .env
        run: echo "${{ secrets.RAILS_ENV_FILE }}" > .env

      - name: Restart Puma
        run: sudo systemctl restart puma
